language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - TARGET=i686-linux-gnu
    - TARGET=x86_64-linux-gnu
    - TARGET=aarch64-linux-gnu
    - TARGET=arm-linux-gnueabihf
    - TARGET=powerpc64le-linux-gnu
    - TARGET=i686-linux-musl
    - TARGET=x86_64-linux-musl
    - TARGET=aarch64-linux-musl
    - TARGET=arm-linux-musleabihf
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-unknown-freebsd11.1
    - TARGET=i686-w64-mingw32
    - TARGET=x86_64-w64-mingw32

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'using Pkg; Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia --color=yes build_tarballs.jl $TARGET

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: floswald/TasBuilder
    tags: true